server {
    listen 80;
    server_name thinkupacademy.ro www.thinkupacademy.ro;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name thinkupacademy.ro www.thinkupacademy.ro;

    ssl_certificate /etc/letsencrypt/live/thinkupacademy.ro/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/thinkupacademy.ro/privkey.pem;

    client_max_body_size 50M;

    location ~ ^/(users|projects|user_projects|goals|materials|files|storage|contact|thumbnails|openSchool|reviews|personal_objectives|feedback|challenges|submissions|warnings) {
        proxy_pass http://backend:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://frontend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;
    }
}
